name: Build Docs

on:
  push:
    branches:
      - main


jobs:
  ghpages:
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools mkdocs-material
          python setup.py develop
      - name: Build
        run: |
          python -m mkdocs build --clean --verbose
      - name: Publish
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
